name: Python CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Downgraded to Python 3.11 for better compatibility

      - name: Upgrade pip, setuptools, and wheel
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools==65.5.0  # Pin setuptools to a compatible version
          python -m pip install wheel

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: List files
        run: |
          ls -R

      - name: Lint code with flake8
        run: |
          pip install flake8
          flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 src --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}/src
        run: |
          pip install pytest
          pytest tests --maxfail=1 --disable-warnings -q

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PowerShell
        uses: actions/setup-powershell@v2

      - name: Deploy to server
        shell: pwsh
        run: |
          echo "Deploying to server..."
          .\deploy-scripts\deploy.ps1