name: Python CI/CD

# Controls when the action will run
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Downgrade to Python 3.11 for compatibility

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel  # Ensure setuptools and wheel are up-to-date
          pip install -r requirements.txt

      - name: Lint code with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run tests
        run: |
          pip install pytest
          pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Ensure consistent Python version for deploy

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel  # Ensure setuptools and wheel are up-to-date
          pip install -r requirements.txt

      - name: Deploy to server
        env:
          DEPLOYMENT_KEY: ${{ secrets.DEPLOYMENT_KEY }}
        run: |
          echo "Deploying to server..."
          # Example deployment command. Replace with your actual deployment commands.
          ssh -i $DEPLOYMENT_KEY user@server 'bash -s' < deploy.sh
